# Generated by Django 5.1.4 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
